export const GET_PPRODUCTS_REQUEST = "GET_PPRODUCTS_REQUEST";
export const GET_PPRODUCTS_SUCCESS = "GET_PPRODUCTS_SUCCESS";
export const GET_PPRODUCTS_FAILURE = "GET_PPRODUCTS_FAILURE";

export const POST_PPRODUCTS_CART_REQUEST = "POST_PPRODUCTS_CART_REQUEST";
export const POST_PPRODUCTS_CART_SUCCESS = "POST_PPRODUCTS_CART_SUCCESS";
export const POST_PPRODUCTS_CART_FAILURE = "POST_PPRODUCTS_CART_FAILURE";